services:
  json-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./components.json:/app/components.json
      - ./routes.json:/app/routes.json
    environment:
      - NODE_ENV=development
    restart: unless-stopped
